### ISSUE TITLE
TypeError: unsupported operand type(s) for %: 'NoneType' and 'dict'

### ISSUE THREAD

**Issue by kiryanenko** [artembo/django-tarantool#7]
Привет увидел, что ты добавил поддержку Django 1.11 - большое тебе спасибо!
У меня при выполнении миграции `python manage.py migrate` возникает такая ошибка:
```
# python manage.py migrate --database=tarantool
Operations to perform:
  Apply all migrations: shared_editor
Running migrations:
  Applying shared_editor.0002_auto_20201229_1637...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 88, in database_forwards
    field,
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django_tarantool/backend/schema.py", line 255, in add_field
    self._remake_table(model, create_field=field)
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django_tarantool/backend/schema.py", line 203, in _remake_table
    self.create_model(new_model)
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 287, in create_model
    self.deferred_sql.append(self._create_fk_sql(model, field, "_fk_%(to_table)s_%(to_column)s"))
  File "/Users/a.kiryanenko/codehub_new/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 983, in _create_fk_sql
    "deferrable": self.connection.ops.deferrable_sql(),
TypeError: unsupported operand type(s) for %: 'NoneType' and 'dict'
```
Это связано с тем, что в `django_tarantool.backend.schema.AbstractDatabaseSchemaEditor` `sql_create_fk ` присваивается значение `None`.
В проекте используется Django 1.11.29.

**Comment by artembo** [comment]
Спасибо за тикет, я поправлю сегодня-завтра.

**Comment by artembo** [comment]
@kiryanenko Еще раз благодарю за тикет, 
предложенные изменения находятся в версии pypi **v0.0.20**

В ближайшее время я планирую настроить ci для тестирование версий django>=1.10,<3.2 с django-tarantool.

Мне было бы интересно узнать про проект, в котором используется django-tarantool, если будет возможность, напиши пожалуйста, мне в телеграм — @artembo, это бы пригодилось для развития пакета.
